require_relative "./simplepokedex/version" 
require_relative "./simplepokedex/API"
require_relative "./simplepokedex/CLI"
require_relative "./simplepokedex/pokemon" 
require "rest-client"
require "json"